name: Build APK Enzeiverse Engine
on: workflow_dispatch

jobs:
  pabrik_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create & Patch Enzeiverse Engine
        run: |
          # 1. Buat project internal
          flutter create --platforms android --project-name enzeiverse_engine .
          
          # 2. Tambah library pendukung
          flutter pub add webview_flutter
          flutter pub add webview_flutter_android
          
          # 3. Patch AndroidManifest (Izin HTTP & Network State)
          # Mengizinkan koneksi HTTP biasa
          sed -i '/<application/s/$/ android:usesCleartextTraffic="true"/' android/app/src/main/AndroidManifest.xml
          
          # Menambah izin Network untuk stabilitas Cache
          sed -i '/<manifest/a \    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"\/>' android/app/src/main/AndroidManifest.xml
          
          # 4. Ganti nama tampilan aplikasi di HP
          sed -i 's/android:label="enzeiverse_engine"/android:label="Enzeiverse Engine"/' android/app/src/main/AndroidManifest.xml

      - name: Build APK
        run: flutter build apk --release

      - name: Simpan Hasil APK
        uses: actions/upload-artifact@v4
        with:
          name: Enzeiverse_Engine_v1
          path: build/app/outputs/flutter-apk/app-release.apk
