name: Build APK Ukari
on: workflow_dispatch

jobs:
  pabrik_apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Update ke v4

      - name: Setup Java
        uses: actions/setup-java@v4 # Update ke v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create & Build
        run: |
          flutter create --platforms android .
          flutter pub add webview_flutter
          flutter build apk --release

      - name: Simpan Hasil
        uses: actions/upload-artifact@v4 # INI YANG DIPERBAIKI (v4)
        with:
          name: APK_UKARI_SUKSES
          path: build/app/outputs/flutter-apk/app-release.apk
